FROM arm32v7/node:12.13.0-alpine

WORKDIR /home/app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY ./ ./
RUN yarn run build

RUN npm prune --production \
  && rm -rf test \
  && find . -type f -name "*.d.ts" -exec rm {} \;

RUN mv src dist

CMD ["node", "dist/index.js"]
