FROM arm32v7/node:12.13.0-alpine

WORKDIR /home/app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY ./ ./
RUN yarn run build

RUN yarn install --production --ignore-scripts --prefer-offline \
  && rm -rf test \
  && find . -type f -name "*.d.ts" -exec rm {} \;

RUN yarn cache clean

RUN mv dist/src/* dist
RUN rm -rf dist/test

CMD ["node", "dist/index.js"]
