FROM arm32v7/node:12.13.0-alpine

RUN apk --update add python

WORKDIR /home/app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --prod
COPY ./ ./
RUN yarn run build


CMD ["node", "dist/src/index.js"]
